# motif02_i1ffl_coherent.py
# Family 6 — Network Motifs / Multiscale
# Coherent type-1 feed-forward loop (C1FFL): X activates Y and Z; Y also activates Z (AND-like integration).
# Multiscale: fast mRNAs, slower proteins, abundant metabolic substrate driving phosphorylation of Z.

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# -------------------------
# (a) Variables globales obligatorias
# -------------------------
MODEL_NAME = "motif02_i1ffl_coherent"

SPECIES_NAMES = [
    "X_mRNA",       # 0 fast, low copy
    "X_protein",    # 1 slower, moderate
    "Y_mRNA",       # 2 fast, low
    "Y_protein",    # 3 slower, low-moderate
    "Z_mRNA",       # 4 fast, low
    "Z_protein",    # 5 slower, moderate
    "S_substrate",  # 6 abundant, slow metabolic substrate (e.g., ATP-like)
    "Z_phospho"     # 7 modified high-copy output state
]

PARAMS = {
    # X transcription & translation
    "k_tx_X": 7.0,
    "d_mX": 3.0,
    "k_tl_X": 6.0,
    "d_X": 0.30,

    # Y transcription activated by X (Hill)
    "k_tx_Y_max": 42.0,
    "K_XY": 45.0,
    "n_XY": 2.0,
    "d_mY": 3.2,
    "k_tl_Y": 7.0,
    "d_Y": 0.50,

    # Z transcription: coherent FFL AND-like (requires X and Y)
    "k_tx_Z_max": 70.0,
    "K_XZ": 35.0,
    "n_XZ": 2.0,
    "K_YZ": 28.0,
    "n_YZ": 2.0,
    "d_mZ": 3.4,
    "k_tl_Z": 8.0,
    "d_Z": 0.25,

    # Substrate-driven phosphorylation cycle for Z (adds multiscale + buffering)
    "k_phos": 0.0065,   # phosphorylation rate constant
    "K_S": 120.0,       # saturation in S
    "k_dephos": 0.35,   # dephosphorylation (fast relative to protein dilution)
    "d_Zp": 0.12,       # clearance/dilution of Z_phospho

    # Substrate homeostasis (abundant, slow)
    "S_prod": 18.0,
    "d_S": 0.015
}

Y0 = np.array([
    0.4,    # X_mRNA
    1.5,    # X_protein
    0.1,    # Y_mRNA
    0.3,    # Y_protein
    0.05,   # Z_mRNA
    0.8,    # Z_protein
    750.0,  # S_substrate (abundant)
    5.0     # Z_phospho
], dtype=float)

TSPAN = (0.0, 90.0)

# -------------------------
# (b) ODE function con firma EXACTA
# -------------------------
def dYdt(t, Y):
    p = PARAMS

    X_m = max(Y[0], 0.0)
    X_p = max(Y[1], 0.0)
    Y_m = max(Y[2], 0.0)
    Y_p = max(Y[3], 0.0)
    Z_m = max(Y[4], 0.0)
    Z_p = max(Y[5], 0.0)
    S   = max(Y[6], 0.0)
    Zph = max(Y[7], 0.0)

    # Hill activations
    act_XY = (X_p**p["n_XY"]) / (p["K_XY"]**p["n_XY"] + X_p**p["n_XY"] + 1e-12)
    act_XZ = (X_p**p["n_XZ"]) / (p["K_XZ"]**p["n_XZ"] + X_p**p["n_XZ"] + 1e-12)
    act_YZ = (Y_p**p["n_YZ"]) / (p["K_YZ"]**p["n_YZ"] + Y_p**p["n_YZ"] + 1e-12)

    # Coherent FFL AND-like integration: Z requires both X and Y
    tx_Z = p["k_tx_Z_max"] * act_XZ * act_YZ

    # Phosphorylation cycle (saturable in substrate)
    sat_S = S / (p["K_S"] + S + 1e-12)
    v_phos = p["k_phos"] * Z_p * sat_S * S   # effective second-order-like at high S
    v_deph = p["k_dephos"] * Zph

    # X module
    dX_m = p["k_tx_X"] - p["d_mX"] * X_m
    dX_p = p["k_tl_X"] * X_m - p["d_X"] * X_p

    # Y module
    tx_Y = p["k_tx_Y_max"] * act_XY
    dY_m = tx_Y - p["d_mY"] * Y_m
    dY_p = p["k_tl_Y"] * Y_m - p["d_Y"] * Y_p

    # Z module
    dZ_m = tx_Z - p["d_mZ"] * Z_m
    dZ_p = p["k_tl_Z"] * Z_m - p["d_Z"] * Z_p - v_phos + v_deph

    # Substrate S: abundant pool, slow turnover; consumed by phosphorylation, regenerated by dephosphorylation
    dS = p["S_prod"] - p["d_S"] * S - v_phos + v_deph

    # Z_phospho: produced by phosphorylation, removed by dephosphorylation and slow clearance
    dZph = v_phos - v_deph - p["d_Zp"] * Zph

    return np.array([dX_m, dX_p, dY_m, dY_p, dZ_m, dZ_p, dS, dZph], dtype=float)


# -------------------------
# (c)(d)(e)(f) En __main__
# -------------------------
if __name__ == "__main__":
    t0, tf = TSPAN
    t_span = (t0, tf)
    t_eval = np.linspace(t0, tf, 2000)

    sol = solve_ivp(dYdt, t_span, Y0, t_eval=t_eval, method="Radau")

    if not sol.success:
        print("WARNING: solve_ivp reported failure:", sol.message)

    Y = sol.y  # shape (n_species, n_time)

    # (e) Micro-audit obligatorio
    labels = []
    for i, name in enumerate(SPECIES_NAMES):
        traj = Y[i, :]
        q80 = float(np.quantile(traj, 0.80))
        q99 = float(np.quantile(traj, 0.99))
        label = 1 if (q80 < 200.0 and q99 < 200.0) else 0
        labels.append(label)
        print(f"{name}: q80={q80:.3f}, q99={q99:.3f} => label={label}")

    n1 = int(sum(labels))
    n0 = int(len(labels) - n1)
    print(f"Summary: label1={n1}, label0={n0}")
    if n1 == 0 or n0 == 0:
        print("WARNING: monoclass labels detected")

    # (f) Plot obligatorio
    plt.figure(figsize=(10, 6))
    for i, name in enumerate(SPECIES_NAMES):
        plt.plot(sol.t, Y[i, :], label=name)
    plt.xlabel("t")
    plt.ylabel("abundance / concentration")
    plt.title(MODEL_NAME)
    plt.legend(loc="best", fontsize=8, ncol=2)
    plt.tight_layout()
    plt.savefig(f"{MODEL_NAME}_preview.png", dpi=160)
    plt.close()

# -------------------------
# (g) Compatibilidad para el auditor
# -------------------------
var_names = SPECIES_NAMES

def model_odes(t, y):
    return dYdt(t, y)
